### ISSUE TITLE
LimitCount extra repo4 - closed first

### ISSUE THREAD

**Issue by anna04test** [anna04test/personal#4]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x9e5d7caa676b6e3ef43d305055812b09708b2432](https://ropsten.etherscan.io/address/0x9e5d7caa676b6e3ef43d305055812b09708b2432)
![QR Code](https://openbounty.status.im:444/qr/anna04test/personal/bounty/4/c2e78a6481df005113491e9ac0be697edf9bc76f46106bf0951271be0f158eed/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
